server:
  port: 8084

spring:
  application:
    name: payment-service

# Payment Simulator Configuration
payment:
  simulator:
    # Success rate percentage (0-100)
    success-rate: 70

    # Processing delay in seconds (min-max)
    delay:
      min: 1
      max: 3

    # Failure scenarios configuration
    failures:
      insufficient-funds-rate: 15    # 15% of failures
      card-declined-rate: 10         # 10% of failures
      network-error-rate: 5          # 5% of failures

    # Enable/disable random failures
    enable-random-failures: true

    # Demo mode - always succeed for specific test cases
    demo-mode: true
    demo-success-emails:
      - "demo@test.com"
      - "success@test.com"
    demo-failure-emails:
      - "fail@test.com"
      - "decline@test.com"

logging:
  level:
    com.fbs.payment: DEBUG