server:
  port: 8082

spring:
  application:
    name: inventory-service
  
  datasource:
    url: jdbc:postgresql://postgres-db:5432/flight_inventory_db
    username: flight_user
    password: flight_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  sql:
    init:
      mode: always

  data:
    redis:
      host: redis-cache
      port: 6379

logging:
  level:
    com.fbs.inventory: DEBUG
    org.springframework.jdbc: DEBUG